##java -jar helloworld-0.0.1-SNAPSHOT.jar --spring.profiles.active=build
##spring:
##  datasource:
##    url: jdbc:mysql://localhost:3306/test?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
##    username: SKUlikelion
##    password: likelion11
##    driver-class-name: com.mysql.cj.jdbc.Driver
##  jpa:
##    hibernate:
##      ddl-auto: none
##    properties:
##      hibernate:
##        show_sql: none
##        format_sql: none
#
#server:
#  port: 8081