spring:
  datasource:
    url: jdbc:mysql://localhost:3306/page2025?useSSL=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Wnsqja6602@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
#    database-platform:

jwt:
  key: asdsdfjowejglwjgijsdfoijwaeiogjweijgipsoadfjiowfgwlkjsdfkjweioufhwoihfgljksdfiouwe

api-key:
  date-checker: 1Kw49paSD5t9RqepmPwQpD8cNSs0I1SzwQlnt5n62oU6vD5P%2Fxnnp2t3I8PwfAa%2BtFY02jbP6yWFcfiKPMRWqA%3D%3D

#server:
#  port: 8081